Refactor help command structure:
AY2324S1-CS2113-T18-2/tp pull request #195
Opened 2023-11-07 16:13 UTC by YFshadaow

- Separate command name and usage into each command class
  - Move Command.java, RawCommand.java to new utils package
  - Refactor parser
  - Make command case-insensitive

2023-11-07 16:17 UTC, YFshadaow commented
The reason I do these modifications are:
  - Intuitively it's a good approach to split the command name and usage into each command class
  - To avoid chunky text blocks in one class

2023-11-07 16:58 UTC, NeoMinWei requested changes
LGTM

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +                                               "Please add a different cashflow.");
is this the correct spacing? should the spacing be 8 spaces?

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +            "add <income/expense> </a AMOUNT> [/t TYPE] [/r RECURRENCE INTERVAL IN DAYS] [/d DESCRIPTION]";
should /t TYPE be in <> brackets instead since its required

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/DeleteCashflowCommand.java
> +               || category.equals(CashflowCategory.RECURRING);
please check spacing here as well

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +                                                   "dining, entertainment, shopping, travel, " +
please check spacing for here

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +                                                   "salary, investments, allowance, others");
check spacing here

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +               || category.equals(CashflowCategory.RECURRING);
spacing

2023-11-07 16:58 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/AddCashflowCommand.java
> +                   || expenseType.equals(ExpenseType.SHOPPING) || expenseType.equals(ExpenseType.TRAVEL)
spacing

2023-11-08 01:10 UTC, ryan1604 approved these changes
LGTM, just fixes the coding standard violations

2023-11-08 01:10 UTC, ryan1604 commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.reflections/reflections
Remove comment if not needed

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/BudgetCommand.java
> +                                                               "or equal to total balance";
spacing

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/BudgetCommand.java
> +                                                "delete, reset, view.");
spacing

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/BudgetCommand.java
> +               command.equals("reset") || command.equals("view");
spacing

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/AddReminderCommand.java
> +            "addreminder </t TYPE> </d DATE>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/AddStockCommand.java
> +            "addstock </s STOCK CODE>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/BalanceCommand.java
> +            "balance";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/DeleteCashflowCommand.java
> +            "delete [income/expense] <INDEX>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/DeleteCashflowCommand.java
> +            "delete [income/expense] <INDEX>";
i think there is an option recurring option for this? check with min wei

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/DeleteStockCommand.java
> +            "deletestock </s STOCK CODE>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/ExitCommand.java
> +            "exit";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/FindCommand.java
> +            "find <KEYWORD>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/ListCommand.java
> +            "list [income/expense]";
should be [income/exspense/recurring] and string can be in one line

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/OverviewCommand.java
> +            "overview";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/SetGoalCommand.java
> +            "set </g AMOUNT> </l LABEL>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/VisCommand.java
> +            "vis </t TYPE> </c pie/bar/radar>";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/WatchListCommand.java
> +            "watchlist";
is it necessary to be in another line?

2023-11-08 01:10 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/utils/CommandManager.java
> +    private static final CommandManager instance = new CommandManager();
might want to follow textbook way of making singleton

2023-11-08 07:14 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/DeleteCashflowCommand.java
> +            "delete [income/expense] <INDEX>";
delete [income/expense] <index> [/r]

2023-11-09 14:32 UTC, closed without merging