Fix bugs
AY2324S1-CS2113-T18-2/tp pull request #212
Opened 2023-11-12 06:57 UTC by hshiah

Fix bugs mentioned in google docs.
Add partial test code.

2023-11-12 07:29 UTC, ryan1604 approved these changes
LGTM

2023-11-12 08:53 UTC, ryan1604 requested changes

2023-11-12 08:53 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/ReminderListCommand.java
> +    private static final java.util.logging.Logger logger = java.util.logging.Logger.
can import java.util.logging.Logger then just use Logger logger instead

2023-11-12 10:10 UTC, NeoMinWei approved these changes
LGTM

2023-11-12 10:10 UTC, NeoMinWei commented on src/test/java/seedu/financialplanner/commands/AddReminderCommandTest.java
> +}
nice testing

2023-11-13 00:54 UTC, ryan1604 commented on src/main/java/seedu/financialplanner/commands/ReminderListCommand.java
> +    private static final Logger logger = java.util.logging.Logger.
Didnt change the second part

2023-11-13 03:04 UTC, ryan1604 approved these changes

2023-11-13 03:05 UTC, merged