Add overview functionality
AY2324S1-CS2113-T18-2/tp pull request #58
Opened 2023-10-15 05:31 UTC by ryan1604

2023-10-15 05:31 UTC, ryan1604 commented
dont merge yet

2023-10-16 11:23 UTC, NeoMinWei submitted a review, later dismissed
deeply nested code from line 37 and 49 of overview command
maybe can implement rounding where user inputs value of 3d.p.?
other than that LGTM

2023-10-17 03:43 UTC, wwweert123 approved these changes
LGTM, Maybe in the AddCashFlowCommand, you can create a method in UI to print the remaining budget or the exceeded budget instead of using showMessage

2023-10-17 03:46 UTC, NeoMinWei requested changes
Very good in abstracting out the Ui elements
However, the code in lines 37 and 49 are STILL DEEPLY NESTED

2023-10-17 03:53 UTC, ryan1604 commented
> Very good in abstracting out the Ui elements However, the code in lines 37 and 49 are STILL DEEPLY NESTED

I believe 2-3 layers of nesting is fine

2023-10-17 03:53 UTC, ryan1604 commented
> LGTM, Maybe in the AddCashFlowCommand, you can create a method in UI to print the remaining budget or the exceeded budget instead of using showMessage

Good idea! I will look into it

2023-10-17 04:12 UTC, NeoMinWei approved these changes

2023-10-17 06:23 UTC, merged

2023-10-25 05:10 UTC, NeoMinWei reviewed
LGTM

2023-10-25 05:10 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/list/Budget.java
> +        return decimalFormat.format(Cashflow.round(currentBudget, 2));
good job on using rounding function to make the value more accurate when displayed in 2d.p.