Add list command
AY2324S1-CS2113-T18-2/tp pull request #89
Opened 2023-10-16 13:43 UTC by YFshadaow

Current behaviour:
`list
You have 4 matching cash flow:
1: Income
   Type: work
   Amount: 5000.00
   Recurring every: 30 days
2: Income
   Type: allowance
   Amount: 123.12
3: Expense
   Type: daily necessities
   Amount: 100.00
   Recurring every: 30 days
4: Expense
   Type: books
   Amount: 123.21
list expense
You have 2 matching cash flow:
1: Expense
   Type: daily necessities
   Amount: 100.00
   Recurring every: 30 days
2: Expense
   Type: books
   Amount: 123.21
list income
You have 2 matching cash flow:
1: Income
   Type: work
   Amount: 5000.00
   Recurring every: 30 days
2: Income
   Type: allowance
   Amount: 123.12
list whatever
Entry must be either income or expense
list`

2023-10-16 14:21 UTC, ryan1604 approved these changes
LGTM

2023-10-16 14:45 UTC, NeoMinWei requested changes
can keep the handleInvalidCategory method in DeleteCashflow Command, I think it looks neater
other than that LGTM

2023-10-17 03:28 UTC, wwweert123 approved these changes
Maybe for the execute function in ListCommand.java you can specify what kind of exception is thrown? This might make it easier for debugging. Eg. FinanicalPlannerException

2023-10-18 14:52 UTC, ryan1604 approved these changes
LGTM

2023-10-18 14:53 UTC, wwweert123 approved these changes
Last PR before milestone 1. We did it guys!

2023-10-18 14:56 UTC, NeoMinWei approved these changes

2023-10-18 14:57 UTC, merged

2023-10-25 05:04 UTC, NeoMinWei reviewed
LGTM

2023-10-25 05:04 UTC, NeoMinWei commented on src/main/java/seedu/financialplanner/commands/DeleteCashflowCommand.java
>      private void handleInvalidCategory(String stringCategory) {
thanks for keeping this method